Video.Web/Controllers/CustomersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Video.Application.Interfaces;
using Video.Domain.Entities;
using Video.Domain.Enums;
using Video.Domain.Utilities;
using Video.Web.ViewModels;

#nullable disable

namespace Video.Web.Controllers;

[Authorize(Roles = Roles.Admin)]
public class CustomersController : Controller
{
    private readonly ICustomerRepository _customer;
    public CustomersController(ICustomerRepository customer)
    {
        _customer = customer;
    }
    public async Task<ActionResult> Index()
    {
        IEnumerable<Customer> customers = await _customer.GetAllCustomersAsync(includeProperties: c => c.MembershipType);
        return View(customers);
    }

    // GET: Customers/Upsert/b86104b6-7205-4d5a-ab83-0eb534c0ae60
    public async Task<IActionResult> Upsert(Guid id)
    {
        IEnumerable<MembershipTypes> membershipTypes = Enumeration.GetAll<MembershipTypes>();

        CustomerViewModel model = new()
        {
            Customer = new(),
            MembershipTypes = membershipTypes.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Value.ToString()
            })
        };

        if (id == Guid.Empty)
        {
            return View(model);
        }
        else
        {
            // update customer
            model.Customer = await _customer.GetCustomerByIdAsync(id);
            foreach (var type in membershipTypes)
            {
                if (type.Value.Equals(model.Customer.MembershipTypeId))
                {
                    model.Customer.MembershipTypeId = (byte)type.Value;
                }
            }
            return View(model);
        }
    }

    // GET: Customers/Upsert/b86104b6-7205-4d5a-ab83-0eb534c0ae60
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Upsert(CustomerViewModel model)
    {
        if (ModelState.IsValid)
        {
            //check whether name is already exists in the database or not
            var customers = await _customer.GetAllAsync();

            foreach (var customer in customers)
            {
                if (customer.FirstName == model.Customer.FirstName
                    && customer.LastName == model.Customer.LastName
                    && customer.Birthdate == model.Customer.Birthdate)
                {
                    //adding error message to ModelState
                    ModelState.AddModelError("FirstName", "Customer Already Exists.");

                    return View(model);
                }
            }

            if (model.Customer.Id.Equals(Guid.Empty))
            {
                await _customer.AddAsync(model.Customer);
                TempData["Success"] = "Customer created successfully.";
            }
            else
            {
                await _customer.UpdateAsync(model.Customer);
                TempData["Success"] = "Customer updated successfully.";
            }

            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }

    // GET: /Customers/Delete/b86104b6-7205-4d5a-ab83-0eb534c0ae60
    public async Task<IActionResult> Delete(Guid id)
    {
        if (id.Equals(Guid.Empty))
        {
            return NotFound();
        }

        Customer customer = await _customer.GetCustomerByIdAsync(id);
        if (customer == null)
        {
            return NotFound();
        }

        return View(customer);
    }

    // POST: /Customers/Delete/b86104b6-7205-4d5a-ab83-0eb534c0ae60
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
        Customer customer = await _customer.GetCustomerByIdAsync(id);
        await _customer.DeleteCustomerByIdAsync(customer.Id);
        TempData["Success"] = "Customer deleted successfully.";

        return RedirectToAction("Index");
    }
}

Video.Web/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using Video.Application.Interfaces;
using Video.Domain.Entities;
using Video.Domain.Utilities;
using Video.Web.ViewModels;

namespace Video.Web.Controllers;

[Authorize]
public class MoviesController : Controller
{
    private readonly IMovieRepository _movie;
    private readonly IGenreRepository _genre;
    private readonly IWebHostEnvironment _hostEnvironment;

    public MoviesController(
        IMovieRepository movie,
        IGenreRepository genre,
        IWebHostEnvironment hostEnvironment)
    {
        _movie = movie;
        _genre = genre;
        _hostEnvironment = hostEnvironment;
    }
    public async Task<IActionResult> Index()
    {
        if (User.IsInRole(Roles.Admin))
            return await Task.FromResult(View("Index"));
        else
            return await Task.FromResult(View("List"));
    }

    // GET: movies/Upsert/b86104b6-7205-4d5a-ab83-0eb534c0ae60
    public async Task<IActionResult> Upsert(int id)
    {
        IEnumerable<Genre> genres = await _genre.GetAllAsync();
        MovieViewModel model = new()
        {
            Movie = new(),
            Genres = genres.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            })
        };

        if (id == 0)
        {
            return View(model);
        }
        else
        {
            // update customer
            model.Movie = await _movie.GetByIdAsync(id);
            return View(model);
        }
    }

    // GET: Customers/Upsert/b86104b6-7205-4d5a-ab83-0eb534c0ae60
    [Authorize(Roles = Roles.Admin)]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Upsert(MovieViewModel model, IFormFile? file)
    {
        if (ModelState.IsValid)
        {
            if (file != null)
            {
                UploadPoster(model, file);
            }

            if (model.Movie!.Id == 0)
            {
                model.Movie.CreatedDate = DateTime.Now;
                await _movie.AddAsync(model.Movie);
                TempData["Success"] = "Movie created successfully.";
            }
            else
            {
                await _movie.UpdateAsync(model.Movie);
                TempData["Success"] = "Movie updated successfully.";
            }

            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }

    public void ResizeImage(IFormFile file, string path)
    {
        using var image = Image.Load(file.OpenReadStream());
        image.Mutate(x => x.Resize(600, 900));
        image.Save(path);
    }

    private void UploadPoster(MovieViewModel model, IFormFile file)
    {
        string wwwRootPath = _hostEnvironment.WebRootPath;

        string fileName = Guid.NewGuid().ToString();
        var uploads = Path.Combine(wwwRootPath, @"uploads\posters");
        var extension = Path.GetExtension(file.FileName).ToLower();

        if (model.Movie!.ImageUrl != null)
        {
            var oldImagePath = Path.Combine(wwwRootPath, model.Movie.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
        }


        using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
        {
            file.CopyTo(fileStreams);
        }

        model.Movie.ImageUrl = @"\uploads\posters\" + fileName + extension;


        ResizeImage(file, Path.Combine(uploads, fileName + extension));


    }
}

Video.Web/Controllers/RentalsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Video.Application.Interfaces;
using Video.Domain.Entities;
using Video.Domain.Utilities;

#nullable disable

namespace Video.Web.Controllers;

[Authorize(Roles = Roles.Admin)]
public class RentalsController : Controller
{
    private readonly IRentalRepository _rental;
    private readonly IMovieRepository _movie;
    public RentalsController(
        IRentalRepository rental,
        IMovieRepository movie)
    {
        _rental = rental;
        _movie = movie;
    }

    public async Task<ActionResult> Index()
    {
        IEnumerable<Rental> rentals = await _rental.GetAllRentalsAsync(filter:null, r=>r.Customer, r=>r.Movie);
        return View(rentals);
    }

    // GET: Customers 
    public async Task<IActionResult> Create()
    {
        return await Task.FromResult(View());
    }


    public async Task<IActionResult> Return(int id)
    {
        if (id == 0)
            return NotFound();

        var rentalInDb = await _rental.GetByIdAsync(id);
 
        var rentals = await _rental.GetAllRentalsAsync(r=>r.Id == id, r => r.Customer, r => r.Movie);

        foreach (var rental in rentals.ToList())
        {
            rental.Movie.InStock++;
            await _movie.UpdateAsync(rental.Movie);
            rental.DateReturned = DateTime.Now;

            await _rental.UpdateAsync(rental);
        }

        return RedirectToAction(nameof(Index));
    }

}

Video.Web/Views/Shared/_Footer.cshtml
<footer class="footer">
    <div class="container-fluid" style="background-color:#032541;">
        <section class="p-3 pt-0">
            <div class="row d-flex align-items-center">
                <div class="col-md-7 col-lg-8 text-center text-md-start">
                    <div class="p-3 text-white">
                        &copy; @DateTime.Now.Year - VideoTek
                    </div>
                </div>
                <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
                    <a class="text-left text-white ml-4" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </div>
        </section>
    </div>
</footer>

Video.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoTek</title>
    @await Html.PartialAsync("_StylesheetPartial")
</head>
<body>
    @await Html.PartialAsync("_NavBar")
    <div class="container">
        <main role="main" class="pb-3">
            @await Html.PartialAsync("_Notification")
            @RenderBody()
        </main>
    </div>
    @await Html.PartialAsync("_Footer")
    @await Html.PartialAsync("_ScriptsPartial")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Video.Web/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Identity
@using Video.Domain.Utilities

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#032541;">
        <div class="container-fluid">
            <a class="navbar-brand text-secondary" asp-area="" asp-controller="Home" asp-action="Index">VideoTek</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                        @if (User.IsInRole(Roles.Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Rentals" asp-action="Index">Rentals</a>
                            </li>
                        }
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
</header> 

Video.Web/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}

@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]');
    </script>
}

Video.Web/Views/Shared/_ScriptsPartial.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js"></script>
<script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.3.1/bloodhound.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.3.1/bloodhound.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.3.1/typeahead.bundle.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.3.1/typeahead.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.3.1/typeahead.jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.3.1/typeahead.jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datejs/1.0/date.min.js"></script>
 
  

Video.Web/Views/Shared/_StylesheetPartial.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
<link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css"/>
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/Video.Web.styles.css" asp-append-version="true" />